server:
  port: '8082'

spring:
  application.name: temperature-monitoring
  datasource:
    username: sa
    url: jdbc:h2:file:~/algasensors-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    password: '123'
  h2:
    console:
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        #Determina quantas mensagens um listener pode ter 'em mãos' por vez
        prefetch: 4
        retry:
          enabled: true
          #Intervalo de tempo entre uma tentativa e outra
          initial-interval: 10s
          max-interval: 30s
          # A cada nova tentativa, dobra o número de tempo de espera - initial-interval até chegar no max-interval
          multiplier: 2
          #Número máximo de tentativas
          #Na prática - 1 tentativa - 10 s / 2 tentativa - 20 s / 3 tentativa 30 s - 4 tentativa - 30 s - Finaliza as tentativas após a 4
          max-attempts: 4